# Generated by Django 3.1.5 on 2021-04-29 08:16

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56, unique=True, verbose_name='Book Title')),
                ('author', models.CharField(max_length=56)),
                ('price', models.IntegerField(default=0, validators=[book.models.validate_price])),
                ('description', models.CharField(max_length=256, verbose_name='Book Description')),
            ],
        ),
    ]
