# Generated by Django 3.1.5 on 2021-04-29 12:25

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(validators=[book.models.validate_price]),
        ),
    ]
